version: '3'

services:
  bank-api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIA6J7LZ3EDGCWCFMWN
      AWS_SECRET_ACCESS_KEY: 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
      CARD_INFO_CONSUMER_URL: http://172.22.121.153:4012